### ISSUE TITLE
Is it possible to replace xenforeignmemory_map with grant table?

### ISSUE THREAD

**Issue by jandryuk** [xcp-ng/uefistored#2]
I'm asking this in case you already know the answer.  Could grant tables be used for shared memory?  Is there a particular reason they wouldn't work?  Do they get reset when transitioning to booting the OS?

You can restrict access to guest memory with grant tables whereas permission for xenforeignmemory_map allows so much more.  Thanks.

**Comment by beshleman** [comment]
I'm not familiar enough with the grant table ABI to say with 100% certainty whether it is feasible or not.  If the implementation would require post-boot calls to the grant table hypercall interface, then it will likely break because Xen can't mux hypercalls between the firmware and OS, so typically runtime services must lack Xen awareness.

What access restrictions did you have in mind?

**Comment by jandryuk** [comment]
Thanks for the reply, @beshleman .  I'll try to look into it more.

If a domain has XSM permission to foreign memory map of another domain, it can map any of the domain's memory.  Grant tables would limit to just the granted memory. There is support in xl to build a domain with one label, and change it to a second one to run. Dom0 could map the first one's memory to build it, but not when running as the second label. I was thinking in terms of making this compatible with that mode of operation.

**Comment by beshleman** [comment]
Keep us posted @jandryuk .  I originally looked at using Argo, but sadly was stopped short due to the limitation I mentioned above.

If you can get away with mapping and unmapping the grant table frame while the machine is still halted from the trapped port I/O, in post-boot context, I honestly can't see why this wouldn't work.

**Comment by jandryuk** [comment]
AWS Nitro has a similar setup (OVMF patches and vmm/host daemon) and pushes the data through PIO when data cannot be mapped:
https://github.com/aws/uefi/blob/main/edk2-stable202211/0023-edk2-stable202211-ExtVarStore-Add-support-for-PIO-transfer.patch

**Comment by stormi** [comment]
Hello @jandryuk. FYI, we are switching to https://github.com/xapi-project/varstored for the next XCP-ng release, and we don't actively develop `uefistored` anymore. `uefistored` was developed at a time when there were no other open source implementations, and then `varstored` was open-sourced by Citrix, and we are switching to it in order avoid maintaining two competing implementations (despite the fact that Bobby did a very good work for `uefistored` and allowed us to have guest Secure Boot support in XCP-ng 8.2.1, where it is still used for the duration of this release's support).

I'll update the project description.

**Comment by jandryuk** [comment]
Thanks @stormi .  I happened to stumble upon the Nitro stuff recently (and it turns out QEMU is implementing a similar host daemon variable store inside QEMU - https://lore.kernel.org/qemu-devel/20231115151242.184645-1-kraxel@redhat.com/).  Then I coincidentally saw this was still open, so I posted to close the loop.

Good to hear about the shared implementation :+1:
